credentials:
  usernames:
    admin:
      email: admin@gmail.com
      name: Admin
      password: $2b$12$1Qkr3K9nMt.bq8Woo4INouYYIaUvLIMvr8fIvZRclpLl1BweMR3JC # To be replaced with hashed password
    pparker:
      email: pparker@gmail.com
      name: Peter Parker
      password: $2b$12$OTS6QN9PR17SWOtTMk8ENOsUmG3QsEGspoNam8UEepFW.2ku87ECu # To be replaced with hashed password
cookie:
  expiry_days: 30
  key:  "lalala" # Must be string
  name: some_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com